[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ratatui = "0.26.3"
uuid = { version = "1.8", features = ["v4", "serde"] }